// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package guidsl;

import Jakarta.util.*;
import java.io.*;
import java.util.*;



abstract class ExprStmt$$dgram extends AstNode {

}



abstract class ExprStmt$$dmain extends  ExprStmt$$dgram  {

    public void visit( Visitor v ) {

        v.action( ((ExprStmt) this) );
    }

}



abstract public class ExprStmt extends  ExprStmt$$dmain  {

   node eharvest() {
	   Util.override( "eharvest()", ((ExprStmt) this) );
		return null;
	}
}
