// Automatically generated code.  Edit at your own risk!
// Generated by bali2jak v2002.09.03.

package guidsl;

import Jakarta.util.*;
import java.io.*;
import java.util.*;



abstract class Vars$$dgram extends AstNode {

}



abstract public class Vars extends  Vars$$dgram  {

    public void visit( Visitor v ) {

        v.action( ((Vars) this) );
    }

}
